import { render, screen } from '@testing-library/react';
import ProviderDashboard from '../components/ProviderDashboard';

// There is an issue in react-bulma-components Select when multiple selection is enabled.
// Despite we properly pass an array to value prop, it keeps checking for a string or number.
// BeforeAll silents the error generated by this issue.
const originalError = console.error

beforeAll(() => {
  jest.spyOn(console, 'error').mockImplementation((...args) => {
    if (typeof args[0] === 'string' && args[0].includes('Failed prop type: Invalid prop `value` supplied to `Select`')) {
      return
    }
    return originalError.call(console, args)
  })
})

afterAll(() => {
  console.error.mockRestore()
})

test('renders welcome message', () => {
  const provider = { name: 'name' };
  const user = { address: 'address', provider: provider };
  const web3 = { utils: { hexToString: function(_) {} } };
  const exchange = { getDataIntelligences: async function(_) { return []; } };

  render(<ProviderDashboard user={user} web3={web3} exchange={exchange}/>);

  const welcome = screen.getByText(/Welcome to Intex./i);
  expect(welcome).toBeInTheDocument();
});
