# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Build smart contracts
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      working-directory: .
      run: |
        npm ci
        npm run build --if-present
        npm test
    - name: Build app
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      working-directory: ./app/react-app
      run: |
        npm ci
        npm run build --if-present
        CI=TRUE npm test
